spring:
  application:
    name: random-sum-service
  zipkin:
    base-url: "http://localhost:9411"
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8080

integrationServices:
  randomNumber1Service:
    getNumber:
      endpoint: "http://localhost:8081/random-number-1/number"
  randomNumber2Service:
    getNumber:
      endpoint: "http://localhost:8082/random-number-2/number"